.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

CFLAGS = -KPIC -D__DECALPHA__ -Dlint $(CDEBUGFLAGS) $(CFLAGS1)

CFLAGS1     = -Iinclude -Ilibmp3lame -Impglib


example: example.o md5.o
	$(CC) $(LDFLAGS) -o example example.o md5.o

md5main: md5main.o md5.o
	$(CC) $(LDFLAGS) -o md5main md5main.o md5.o

clean:
	rm -f example.o md5.o md5main.o
