#!/bin/sh
rm -f alsa.def
cat<<NNNN>>alsa.def
# Do not edit alsa.def file!!! 
# alsa.def is automatically generated by make_alsa.sh.
# Edit make_alsa.sh to modify alsa.def!
# 
# Uncomment following line to enable volume and mixer for 
# systems with broken PCM mixer
#OSS_OPTIONS = -DOSS_DSP_MIXER_BROKEN
NNNN

# Below is autoconfigured during build, and should not
# need to be manually configured.
if [ -f /usr/include/alsa/asoundlib.h ]; then
cat<<NNNN>>alsa.def
ALSA_DEFINES = -DALSA
ALSA_LIB     = -lasound
NNNN
fi

exit 0
